In [1]:
import pandas as pd
import plotly.offline as po
import plotly.graph_objects as go  

df = pd.read_csv("https://raw.githubusercontent.com/datasets/covid-19/master/data/time-series-19-covid-combined.csv")
df.Date = pd.to_datetime(df.Date, format="%Y-%m-%d")
df.head()

,Date,Country/Region,Province/State,Lat,Long,Confirmed,Recovered,Deaths
0,2020-01-22,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0
1,2020-01-23,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0
2,2020-01-24,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0
3,2020-01-25,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0
4,2020-01-26,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0

In [ ]:
df2 = pd.read_csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv")
df2.head()

In [ ]:
df3=pd.read_csv("https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/raw/master/all/all.csv")
df3.head()

In [2]:
df4 = pd.read_csv("https://raw.githubusercontent.com/datasets/covid-19/master/data/us_confirmed.csv")
df4.head()

,UID,iso2,iso3,code3,FIPS,Admin2,Lat,Combined_Key,Date,Case,Long,Country/Region,Province/State
0,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",2020-01-22,0,-170.132,US,American Samoa
1,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",2020-01-23,0,-170.132,US,American Samoa
2,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",2020-01-24,0,-170.132,US,American Samoa
3,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",2020-01-25,0,-170.132,US,American Samoa
4,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",2020-01-26,0,-170.132,US,American Samoa

In [3]:
df5 = pd.read_csv("https://raw.githubusercontent.com/datasets/covid-19/master/data/us_deaths.csv")
df5.head()

,UID,iso2,iso3,code3,FIPS,Admin2,Lat,Combined_Key,Population,Date,Case,Long,Country/Region,Province/State
0,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",55641,2020-01-22,0,-170.132,US,American Samoa
1,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",55641,2020-01-23,0,-170.132,US,American Samoa
2,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",55641,2020-01-24,0,-170.132,US,American Samoa
3,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",55641,2020-01-25,0,-170.132,US,American Samoa
4,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",55641,2020-01-26,0,-170.132,US,American Samoa

In [ ]:
pd.concat([df4,df5]).head()

In [ ]:
df4.shape

In [ ]:
df5.shape

In [4]:
df4.rename(columns={"Case":"Confirmed"},inplace=True)
df4["Deaths"] =df5.Case
df4["Population"] = df5.Population
df4["Recovered"] = 0.0
df4.head()

,UID,iso2,iso3,code3,FIPS,Admin2,Lat,Combined_Key,Date,Confirmed,Long,Country/Region,Province/State,Deaths,Population,Recovered
0,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",2020-01-22,0,-170.132,US,American Samoa,0,55641,0.0
1,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",2020-01-23,0,-170.132,US,American Samoa,0,55641,0.0
2,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",2020-01-24,0,-170.132,US,American Samoa,0,55641,0.0
3,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",2020-01-25,0,-170.132,US,American Samoa,0,55641,0.0
4,16,AS,ASM,16,60.0,NaN,-14.271,"American Samoa, US",2020-01-26,0,-170.132,US,American Samoa,0,55641,0.0

In [5]:
df6 = df4[["Date","Lat","Long","Confirmed","Recovered","Deaths","Country/Region","Province/State"]].copy()
df6.Date = pd.to_datetime(df6.Date, format="%Y-%m-%d")
df7 = pd.concat([df,df6]).copy()
df7.head()

,Date,Country/Region,Province/State,Lat,Long,Confirmed,Recovered,Deaths
0,2020-01-22,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0
1,2020-01-23,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0
2,2020-01-24,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0
3,2020-01-25,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0
4,2020-01-26,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0

In [ ]:
tmp = pd.concat([df,df6])
tmp2 = tmp.drop(tmp[(tmp["Country/Region"] == "US") & (tmp["Province/State"].isnull())].index)
tmp2[(tmp2["Country/Region"] == "US") & (tmp2["Province/State"].isnull())]

In [99]:
country_pairs = set(list(map(tuple,df7[["Country/Region","Province/State"]].values)))

In [108]:
import requests as rq
import json
# api-endpoint 
URL = "https://restcountries.eu/rest/v2/name/"
  
# location given here 
location = "Burma"
  
# # defining a params dict for the parameters to be sent to the API 
# PARAMS = {'address':location} 
  
# sending get request and saving the response as response object 
r =rq.get(url = URL + location) 
  
# extracting data in json f
r.json()

[{'name': 'Myanmar',
  'topLevelDomain': ['.mm'],
  'alpha2Code': 'MM',
  'alpha3Code': 'MMR',
  'callingCodes': ['95'],
  'capital': 'Naypyidaw',
  'altSpellings': ['MM',
   'Burma',
   'Republic of the Union of Myanmar',
   'Pyidaunzu Thanmăda Myăma Nainngandaw'],
  'region': 'Asia',
  'subregion': 'South-Eastern Asia',
  'population': 51419420,
  'latlng': [22.0, 98.0],
  'demonym': 'Burmese',
  'area': 676578.0,
  'gini': None,
  'timezones': ['UTC+06:30'],
  'borders': ['BGD', 'CHN', 'IND', 'LAO', 'THA'],
  'nativeName': 'Myanma',
  'numericCode': '104',
  'currencies': [{'code': 'MMK', 'name': 'Burmese kyat', 'symbol': 'Ks'}],
  'languages': [{'iso639_1': 'my',
    'iso639_2': 'mya',
    'name': 'Burmese',
    'nativeName': 'ဗမာစာ'}],
  'translations': {'de': 'Myanmar',
   'es': 'Myanmar',
   'fr': 'Myanmar',
   'ja': 'ミャンマー',
   'it': 'Birmania',
   'br': 'Myanmar',
   'pt': 'Myanmar',
   'nl': 'Myanmar',
   'hr': 'Mijanmar',
   'fa': 'میانمار'},
  'flag': 'https://restcountries.eu/data/mmr.svg',
  'regionalBlocs': [{'acronym': 'ASEAN',
    'name': 'Association of Southeast Asian Nations',
    'otherAcronyms': [],
    'otherNames': []}],
  'cioc': 'MYA'}]

In [119]:
URL = "https://restcountries.eu/rest/v2/name/"
cinfo = {}
for country,state in list(country_pairs)[:10]:
    tmp_country = ""
    if state is np.NaN:
        if country == "Congo (Brazzaville)":
            tmp_country = "Congo-Brazzaville"
        elif country == "Congo (Kinshasa)":
            tmp_country = "Congo-Kinshasa"
        elif country == "Czechia":
            tmp_country =  "Czech Republic"
        elif country in ["Diamond Princess","MS Zaandam"]:
            continue
        elif country == "Korea, South":
            tmp_country = "Korea (Republic of)"
        elif country == "North Macedonia":
            tmp_country = "Republic of Macedonia"
        elif country == "Taiwan*":
            tmp_country = "Taiwan"
        elif country == "West Bank and Gaza":
            tmp_country = "Palestine"
        elif country == "US":
            tmp_country = "United States of America"
        elif country == "India":
            tmp_country = "Republic of India"
        else:
            tmp_country = country
    else:
        tmp_country = state
    try:
        r=rq.get(url = URL + tmp_country).json()
        population = r[0]['population']
        region = r[0]['region']
        subregion = r[0]['subregion'].replace(" ","_")
        code = r[0]['alpha3Code']
        print(country,population,code)
        if country in cinfo:
            continue
        else:
            cinfo[country] = [population,region,subregion,code]     
    except:
        print(f'problem with {country}')
cinfo

United Kingdom 33140 GIB
Burma 51419420 MMR
Madagascar 22434363 MDG
problem with Canada
problem with US
Niger 20715000 NER
problem with US
Mexico 122273473 MEX
problem with China
problem with US

{'United Kingdom': [33140, 'Europe', 'Southern_Europe', 'GIB'],
 'Burma': [51419420, 'Asia', 'South-Eastern_Asia', 'MMR'],
 'Madagascar': [22434363, 'Africa', 'Eastern_Africa', 'MDG'],
 'Niger': [20715000, 'Africa', 'Western_Africa', 'NER'],
 'Mexico': [122273473, 'Americas', 'Central_America', 'MEX']}

In [76]:
with open("test.json","w") as w:
    json.dump(cinfo,w)

In [125]:
print(rq.get(url = "https://en.wikipedia.org/wiki/Alabama"))

<Response [200]>

In [34]:
import numpy as np

In [43]:
df8 = df7.copy()
df8["Population"] = 0.0
df8["Region"] = np.nan
df8["Sub-Region"] = np.nan
df8["ISO3"] = np.nan
for country in countries:
    if country in cinfo:
        df8.loc[df8["Country/Region"] == country,["Population","Region","Sub-Region","ISO3"]] = cinfo[country][:]
#         df8.loc[df8["Country/Region"] == country,"Region"] = cinfo[country][1]
#         df8.loc[df8["Country/Region"] == country,"Sub-Region"] = cinfo[country][2]
#         df8.loc[df8["Country/Region"] == country,"ISO3"] = cinfo[country][3]
    else:
        pass
df8.head()

,Date,Country/Region,Province/State,Lat,Long,Confirmed,Recovered,Deaths,Population,Region,Sub-Region,ISO3
0,2020-01-22,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0,27657145.0,Asia,Southern_Asia,AFG
1,2020-01-23,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0,27657145.0,Asia,Southern_Asia,AFG
2,2020-01-24,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0,27657145.0,Asia,Southern_Asia,AFG
3,2020-01-25,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0,27657145.0,Asia,Southern_Asia,AFG
4,2020-01-26,Afghanistan,NaN,33.0,65.0,0.0,0.0,0.0,27657145.0,Asia,Southern_Asia,AFG

In [46]:
df8["Sub-Region"].unique()

array(['Southern_Asia', 'Southern_Europe', 'Northern_Africa',
       'Middle_Africa', 'Caribbean', 'South_America', 'Western_Asia',
       'Australia_and_New_Zealand', 'Western_Europe', 'Eastern_Europe',
       'Central_America', 'Western_Africa', 'Southern_Africa',
       'South-Eastern_Asia', 'Eastern_Africa', 'Northern_America',
       'Eastern_Asia', 'Northern_Europe', nan, 'Melanesia',
       'Central_Asia'], dtype=object)

In [53]:
df8[(df8["Country/Region"] == "US") & (df8["Province/State"].isnull())]

,Date,Country/Region,Province/State,Lat,Long,Confirmed,Recovered,Deaths,Population,Region,Sub-Region,ISO3
20160,2020-01-22,US,NaN,37.0902,-95.7129,1.0,0.0,0.0,323947000.0,Americas,Northern_America,USA
20161,2020-01-23,US,NaN,37.0902,-95.7129,1.0,0.0,0.0,323947000.0,Americas,Northern_America,USA
20162,2020-01-24,US,NaN,37.0902,-95.7129,2.0,0.0,0.0,323947000.0,Americas,Northern_America,USA
20163,2020-01-25,US,NaN,37.0902,-95.7129,2.0,0.0,0.0,323947000.0,Americas,Northern_America,USA
20164,2020-01-26,US,NaN,37.0902,-95.7129,5.0,0.0,0.0,323947000.0,Americas,Northern_America,USA
...,...,...,...,...,...,...,...,...,...,...,...,...
20239,2020-04-10,US,NaN,37.0902,-95.7129,496535.0,28790.0,18586.0,323947000.0,Americas,Northern_America,USA
20240,2020-04-11,US,NaN,37.0902,-95.7129,526396.0,31270.0,20463.0,323947000.0,Americas,Northern_America,USA
20241,2020-04-12,US,NaN,37.0902,-95.7129,555313.0,32988.0,22020.0,323947000.0,Americas,Northern_America,USA
20242,2020-04-13,US,NaN,37.0902,-95.7129,580619.0,43482.0,23529.0,323947000.0,Americas,Northern_America,USA
20243,2020-04-14,US,NaN,37.0902,-95.7129,607670.0,47763.0,25832.0,323947000.0,Americas,Northern_America,USA

In [49]:
rq.get("https://raw.githubusercontent.com/gregory1506/DashPlotly/master/test.json").json()

{'Afghanistan': [27657145, 'Asia', 'Southern_Asia', 'AFG'],
 'Albania': [2886026, 'Europe', 'Southern_Europe', 'ALB'],
 'Algeria': [40400000, 'Africa', 'Northern_Africa', 'DZA'],
 'Andorra': [78014, 'Europe', 'Southern_Europe', 'AND'],
 'Angola': [25868000, 'Africa', 'Middle_Africa', 'AGO'],
 'Antigua and Barbuda': [86295, 'Americas', 'Caribbean', 'ATG'],
 'Argentina': [43590400, 'Americas', 'South_America', 'ARG'],
 'Armenia': [2994400, 'Asia', 'Western_Asia', 'ARM'],
 'Australia': [24117360, 'Oceania', 'Australia_and_New_Zealand', 'AUS'],
 'Austria': [8725931, 'Europe', 'Western_Europe', 'AUT'],
 'Azerbaijan': [9730500, 'Asia', 'Western_Asia', 'AZE'],
 'Bahamas': [378040, 'Americas', 'Caribbean', 'BHS'],
 'Bahrain': [1404900, 'Asia', 'Western_Asia', 'BHR'],
 'Bangladesh': [161006790, 'Asia', 'Southern_Asia', 'BGD'],
 'Barbados': [285000, 'Americas', 'Caribbean', 'BRB'],
 'Belarus': [9498700, 'Europe', 'Eastern_Europe', 'BLR'],
 'Belgium': [11319511, 'Europe', 'Western_Europe', 'BEL'],
 'Belize': [370300, 'Americas', 'Central_America', 'BLZ'],
 'Benin': [10653654, 'Africa', 'Western_Africa', 'BEN'],
 'Bhutan': [775620, 'Asia', 'Southern_Asia', 'BTN'],
 'Bolivia': [10985059, 'Americas', 'South_America', 'BOL'],
 'Bosnia and Herzegovina': [3531159, 'Europe', 'Southern_Europe', 'BIH'],
 'Botswana': [2141206, 'Africa', 'Southern_Africa', 'BWA'],
 'Brazil': [206135893, 'Americas', 'South_America', 'BRA'],
 'Brunei': [411900, 'Asia', 'South-Eastern_Asia', 'BRN'],
 'Bulgaria': [7153784, 'Europe', 'Eastern_Europe', 'BGR'],
 'Burkina Faso': [19034397, 'Africa', 'Western_Africa', 'BFA'],
 'Burma': [51419420, 'Asia', 'South-Eastern_Asia', 'MMR'],
 'Burundi': [10114505, 'Africa', 'Eastern_Africa', 'BDI'],
 'Cabo Verde': [531239, 'Africa', 'Western_Africa', 'CPV'],
 'Cambodia': [15626444, 'Asia', 'South-Eastern_Asia', 'KHM'],
 'Cameroon': [22709892, 'Africa', 'Middle_Africa', 'CMR'],
 'Canada': [36155487, 'Americas', 'Northern_America', 'CAN'],
 'Central African Republic': [4998000, 'Africa', 'Middle_Africa', 'CAF'],
 'Chad': [14497000, 'Africa', 'Middle_Africa', 'TCD'],
 'Chile': [18191900, 'Americas', 'South_America', 'CHL'],
 'China': [1377422166, 'Asia', 'Eastern_Asia', 'CHN'],
 'Colombia': [48759958, 'Americas', 'South_America', 'COL'],
 'Congo (Brazzaville)': [4741000, 'Africa', 'Middle_Africa', 'COG'],
 'Congo (Kinshasa)': [85026000, 'Africa', 'Middle_Africa', 'COD'],
 'Costa Rica': [4890379, 'Americas', 'Central_America', 'CRI'],
 "Cote d'Ivoire": [22671331, 'Africa', 'Western_Africa', 'CIV'],
 'Croatia': [4190669, 'Europe', 'Southern_Europe', 'HRV'],
 'Cuba': [11239004, 'Americas', 'Caribbean', 'CUB'],
 'Cyprus': [847000, 'Europe', 'Southern_Europe', 'CYP'],
 'Czechia': [10558524, 'Europe', 'Eastern_Europe', 'CZE'],
 'Denmark': [5717014, 'Europe', 'Northern_Europe', 'DNK'],
 'Djibouti': [900000, 'Africa', 'Eastern_Africa', 'DJI'],
 'Dominica': [71293, 'Americas', 'Caribbean', 'DMA'],
 'Dominican Republic': [10075045, 'Americas', 'Caribbean', 'DOM'],
 'Ecuador': [16545799, 'Americas', 'South_America', 'ECU'],
 'Egypt': [91290000, 'Africa', 'Northern_Africa', 'EGY'],
 'El Salvador': [6520675, 'Americas', 'Central_America', 'SLV'],
 'Equatorial Guinea': [1222442, 'Africa', 'Middle_Africa', 'GNQ'],
 'Eritrea': [5352000, 'Africa', 'Eastern_Africa', 'ERI'],
 'Estonia': [1315944, 'Europe', 'Northern_Europe', 'EST'],
 'Eswatini': [1132657, 'Africa', 'Southern_Africa', 'SWZ'],
 'Ethiopia': [92206005, 'Africa', 'Eastern_Africa', 'ETH'],
 'Fiji': [867000, 'Oceania', 'Melanesia', 'FJI'],
 'Finland': [5491817, 'Europe', 'Northern_Europe', 'FIN'],
 'France': [66710000, 'Europe', 'Western_Europe', 'FRA'],
 'Gabon': [1802278, 'Africa', 'Middle_Africa', 'GAB'],
 'Gambia': [1882450, 'Africa', 'Western_Africa', 'GMB'],
 'Georgia': [3720400, 'Asia', 'Western_Asia', 'GEO'],
 'Germany': [81770900, 'Europe', 'Western_Europe', 'DEU'],
 'Ghana': [27670174, 'Africa', 'Western_Africa', 'GHA'],
 'Greece': [10858018, 'Europe', 'Southern_Europe', 'GRC'],
 'Grenada': [103328, 'Americas', 'Caribbean', 'GRD'],
 'Guatemala': [16176133, 'Americas', 'Central_America', 'GTM'],
 'Guinea-Bissau': [1547777, 'Africa', 'Western_Africa', 'GNB'],
 'Guinea': [1222442, 'Africa', 'Middle_Africa', 'GNQ'],
 'Guyana': [746900, 'Americas', 'South_America', 'GUY'],
 'Haiti': [11078033, 'Americas', 'Caribbean', 'HTI'],
 'Holy See': [451, 'Europe', 'Southern_Europe', 'VAT'],
 'Honduras': [8576532, 'Americas', 'Central_America', 'HND'],
 'Hungary': [9823000, 'Europe', 'Eastern_Europe', 'HUN'],
 'Iceland': [334300, 'Europe', 'Northern_Europe', 'ISL'],
 'India': [3000, 'Africa', 'Eastern_Africa', 'IOT'],
 'Indonesia': [258705000, 'Asia', 'South-Eastern_Asia', 'IDN'],
 'Iran': [79369900, 'Asia', 'Southern_Asia', 'IRN'],
 'Iraq': [37883543, 'Asia', 'Western_Asia', 'IRQ'],
 'Ireland': [6378000, 'Europe', 'Northern_Europe', 'IRL'],
 'Israel': [8527400, 'Asia', 'Western_Asia', 'ISR'],
 'Italy': [60665551, 'Europe', 'Southern_Europe', 'ITA'],
 'Jamaica': [2723246, 'Americas', 'Caribbean', 'JAM'],
 'Japan': [126960000, 'Asia', 'Eastern_Asia', 'JPN'],
 'Jordan': [9531712, 'Asia', 'Western_Asia', 'JOR'],
 'Kazakhstan': [17753200, 'Asia', 'Central_Asia', 'KAZ'],
 'Kenya': [47251000, 'Africa', 'Eastern_Africa', 'KEN'],
 'Korea, South': [50801405, 'Asia', 'Eastern_Asia', 'KOR'],
 'Kosovo': [1733842, 'Europe', 'Eastern_Europe', 'KOS'],
 'Kuwait': [4183658, 'Asia', 'Western_Asia', 'KWT'],
 'Kyrgyzstan': [6047800, 'Asia', 'Central_Asia', 'KGZ'],
 'Laos': [6492400, 'Asia', 'South-Eastern_Asia', 'LAO'],
 'Latvia': [1961600, 'Europe', 'Northern_Europe', 'LVA'],
 'Lebanon': [5988000, 'Asia', 'Western_Asia', 'LBN'],
 'Liberia': [4615000, 'Africa', 'Western_Africa', 'LBR'],
 'Libya': [6385000, 'Africa', 'Northern_Africa', 'LBY'],
 'Liechtenstein': [37623, 'Europe', 'Western_Europe', 'LIE'],
 'Lithuania': [2872294, 'Europe', 'Northern_Europe', 'LTU'],
 'Luxembourg': [576200, 'Europe', 'Western_Europe', 'LUX'],
 'Madagascar': [22434363, 'Africa', 'Eastern_Africa', 'MDG'],
 'Malawi': [16832910, 'Africa', 'Eastern_Africa', 'MWI'],
 'Malaysia': [31405416, 'Asia', 'South-Eastern_Asia', 'MYS'],
 'Maldives': [344023, 'Asia', 'Southern_Asia', 'MDV'],
 'Mali': [18135000, 'Africa', 'Western_Africa', 'MLI'],
 'Malta': [425384, 'Europe', 'Southern_Europe', 'MLT'],
 'Mauritania': [3718678, 'Africa', 'Western_Africa', 'MRT'],
 'Mauritius': [1262879, 'Africa', 'Eastern_Africa', 'MUS'],
 'Mexico': [122273473, 'Americas', 'Central_America', 'MEX'],
 'Moldova': [3553100, 'Europe', 'Eastern_Europe', 'MDA'],
 'Monaco': [38400, 'Europe', 'Western_Europe', 'MCO'],
 'Mongolia': [3093100, 'Asia', 'Eastern_Asia', 'MNG'],
 'Montenegro': [621810, 'Europe', 'Southern_Europe', 'MNE'],
 'Morocco': [33337529, 'Africa', 'Northern_Africa', 'MAR'],
 'Mozambique': [26423700, 'Africa', 'Eastern_Africa', 'MOZ'],
 'Namibia': [2324388, 'Africa', 'Southern_Africa', 'NAM'],
 'Nepal': [28431500, 'Asia', 'Southern_Asia', 'NPL'],
 'Netherlands': [17019800, 'Europe', 'Western_Europe', 'NLD'],
 'New Zealand': [4697854, 'Oceania', 'Australia_and_New_Zealand', 'NZL'],
 'Nicaragua': [6262703, 'Americas', 'Central_America', 'NIC'],
 'Niger': [20715000, 'Africa', 'Western_Africa', 'NER'],
 'Nigeria': [186988000, 'Africa', 'Western_Africa', 'NGA'],
 'North Macedonia': [2058539, 'Europe', 'Southern_Europe', 'MKD'],
 'Norway': [5223256, 'Europe', 'Northern_Europe', 'NOR'],
 'Oman': [4420133, 'Asia', 'Western_Asia', 'OMN'],
 'Pakistan': [194125062, 'Asia', 'Southern_Asia', 'PAK'],
 'Panama': [3814672, 'Americas', 'Central_America', 'PAN'],
 'Papua New Guinea': [8083700, 'Oceania', 'Melanesia', 'PNG'],
 'Paraguay': [6854536, 'Americas', 'South_America', 'PRY'],
 'Peru': [31488700, 'Americas', 'South_America', 'PER'],
 'Philippines': [103279800, 'Asia', 'South-Eastern_Asia', 'PHL'],
 'Poland': [38437239, 'Europe', 'Eastern_Europe', 'POL'],
 'Portugal': [10374822, 'Europe', 'Southern_Europe', 'PRT'],
 'Qatar': [2587564, 'Asia', 'Western_Asia', 'QAT'],
 'Romania': [19861408, 'Europe', 'Eastern_Europe', 'ROU'],
 'Russia': [146599183, 'Europe', 'Eastern_Europe', 'RUS'],
 'Rwanda': [11553188, 'Africa', 'Eastern_Africa', 'RWA'],
 'Saint Kitts and Nevis': [46204, 'Americas', 'Caribbean', 'KNA'],
 'Saint Lucia': [186000, 'Americas', 'Caribbean', 'LCA'],
 'Saint Vincent and the Grenadines': [109991, 'Americas', 'Caribbean', 'VCT'],
 'San Marino': [33005, 'Europe', 'Southern_Europe', 'SMR'],
 'Sao Tome and Principe': [187356, 'Africa', 'Middle_Africa', 'STP'],
 'Saudi Arabia': [32248200, 'Asia', 'Western_Asia', 'SAU'],
 'Senegal': [14799859, 'Africa', 'Western_Africa', 'SEN'],
 'Serbia': [7076372, 'Europe', 'Southern_Europe', 'SRB'],
 'Seychelles': [91400, 'Africa', 'Eastern_Africa', 'SYC'],
 'Sierra Leone': [7075641, 'Africa', 'Western_Africa', 'SLE'],
 'Singapore': [5535000, 'Asia', 'South-Eastern_Asia', 'SGP'],
 'Slovakia': [5426252, 'Europe', 'Eastern_Europe', 'SVK'],
 'Slovenia': [2064188, 'Europe', 'Southern_Europe', 'SVN'],
 'Somalia': [11079000, 'Africa', 'Eastern_Africa', 'SOM'],
 'South Africa': [55653654, 'Africa', 'Southern_Africa', 'ZAF'],
 'South Sudan': [12131000, 'Africa', 'Middle_Africa', 'SSD'],
 'Spain': [46438422, 'Europe', 'Southern_Europe', 'ESP'],
 'Sri Lanka': [20966000, 'Asia', 'Southern_Asia', 'LKA'],
 'Sudan': [12131000, 'Africa', 'Middle_Africa', 'SSD'],
 'Suriname': [541638, 'Americas', 'South_America', 'SUR'],
 'Sweden': [9894888, 'Europe', 'Northern_Europe', 'SWE'],
 'Switzerland': [8341600, 'Europe', 'Western_Europe', 'CHE'],
 'Syria': [18564000, 'Asia', 'Western_Asia', 'SYR'],
 'Taiwan*': [23503349, 'Asia', 'Eastern_Asia', 'TWN'],
 'Tanzania': [55155000, 'Africa', 'Eastern_Africa', 'TZA'],
 'Thailand': [65327652, 'Asia', 'South-Eastern_Asia', 'THA'],
 'Timor-Leste': [1167242, 'Asia', 'South-Eastern_Asia', 'TLS'],
 'Togo': [7143000, 'Africa', 'Western_Africa', 'TGO'],
 'Trinidad and Tobago': [1349667, 'Americas', 'Caribbean', 'TTO'],
 'Tunisia': [11154400, 'Africa', 'Northern_Africa', 'TUN'],
 'Turkey': [78741053, 'Asia', 'Western_Asia', 'TUR'],
 'US': [323947000, 'Americas', 'Northern_America', 'USA'],
 'Uganda': [33860700, 'Africa', 'Eastern_Africa', 'UGA'],
 'Ukraine': [42692393, 'Europe', 'Eastern_Europe', 'UKR'],
 'United Arab Emirates': [9856000, 'Asia', 'Western_Asia', 'ARE'],
 'United Kingdom': [65110000, 'Europe', 'Northern_Europe', 'GBR'],
 'Uruguay': [3480222, 'Americas', 'South_America', 'URY'],
 'Uzbekistan': [31576400, 'Asia', 'Central_Asia', 'UZB'],
 'Venezuela': [31028700, 'Americas', 'South_America', 'VEN'],
 'Vietnam': [92700000, 'Asia', 'South-Eastern_Asia', 'VNM'],
 'West Bank and Gaza': [4682467, 'Asia', 'Western_Asia', 'PSE'],
 'Western Sahara': [510713, 'Africa', 'Northern_Africa', 'ESH'],
 'Yemen': [27478000, 'Asia', 'Western_Asia', 'YEM'],
 'Zambia': [15933883, 'Africa', 'Eastern_Africa', 'ZMB'],
 'Zimbabwe': [14240168, 'Africa', 'Eastern_Africa', 'ZWE']}

In [61]:
df8.Date.unique()[0]

numpy.datetime64('2020-01-22T00:00:00.000000000')

In [62]:
import datetime as dt

In [67]:
np.datetime_as_string(df8.Date.min(),unit="D")

TypeError: input must have type NumPy datetime

In [73]:
str(df8.Date.min())[:10]

'2020-01-22'

In [118]:
df7[df7["Country/Region"] == "Burma"]["Province/State"].values[0] is np.NaN

True